/** @type {import('tailwindcss').Config} */
export default {
  content: [
     "./src/pages//*.{js,ts,jsx,tsx,mdx}",
    "./src/pages/blogs/*.{js,ts,jsx,tsx,mdx}",
    "./src/pages/services/*.{js,ts,jsx,tsx,mdx}",
    "./src/pages/state-to-state/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/Home/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/CommonComponents/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/SlugPage/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/Contact/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/Blog/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/State/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/Cars/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/State-to-State/*.{js,ts,jsx,tsx,mdx}",
    "./src/app//*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    // Common utility classes used dynamically or via CMS
    'text-center',
    'text-left',
    'text-right',
    'bg-white',
    'bg-black',
    'bg-[#F4511E]',
    'hover:bg-[#D84315]',
    'text-white',
    'text-black',
    'rounded',
    'rounded-full',
    'font-bold',
    'font-medium',
    'py-3',
    'px-8',
    'w-full',
    'md:w-32',
    'h-12',
    'transition-all',
    'duration-300',
    'transform',
    'hover:scale-105',
    'backdrop-blur-sm',
    'border-2',
    'border-rapidcolor',
    'sr-only',
    // Regex for commonly used patterns
    /^bg-/,
    /^text-/,
    /^hover:/,
    /^rounded/,
    /^w-/,
    /^h-/,
    /^px-/,
    /^py-/,
    /^flex/,
    /^items-/,
    /^justify-/,
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        navbg: "var(--navbg)",
        navborder: "var(--navborder)",
        rapidcolor: "var(--rapid)",
        h1color: "var(--h1colors)",
        lightgray: "#e4e4e4",
      },
      boxShadow: {
        "3d": "5px 5px 10px rgba(0, 0, 0, 0.2), -5px -5px 10px rgba(0, 0, 0, 0.1)",
      },
      fontFamily: {
        sans: ["var(--font-custom)", "sans-serif"],
      },
      keyframes: {
        zoomBlinkForm: {
          "0%": { transform: "scale(0.8)", opacity: 1 },
          "100%": { transform: "scale(1)", opacity: 1 },
        },
        zoomBlinkNumber: {
          "0%, 100%": { transform: "scale(1)", opacity: 1 },
          "50%": { transform: "scale(1.1)", opacity: 1 },
        },
      },
      animation: {
        zoomBlinkForm: "zoomBlinkForm 1s 1",
        zoomBlinkNumber: "zoomBlinkNumber 1s infinite 1s",
      },
    },
  },
  plugins: [],
};